---
# tasks file for osp.servers

- name: create osp servers
  os_server:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    image: "{{ item.image }}"
    flavor: "{{ item.flavor }}"
    network: 'int_network'
    floating_ip_pools: 'ext_network'
    userdata: "{{ user_data }}"
    security_groups: "{{ item.security_group }}"
    key_name: "{{ item.key_name }}"
    meta: "{{ item.meta }}"
  loop: "{{ osp_servers }}"

# Add floating IP to Servers
- name: Wait for server to be available
  os_server_facts:
    server: "{{ item.name }}"
  register: results
  until: openstack_servers.0.status == "ACTIVE"
  retries: 120
  delay: 5  
  loop: "{{ osp_servers }}"
